-
  name: 'Install and configure FirewallD'
  hosts: target1
  tasks:
    -
      name: 'Install FirewallD'
      apt:
        name: firewalld
        state: present
    -
      name: 'Start the firewallD service'
      service:
        name: firewalld
        state: started
    -
      name: 'Enable service firewalld'
      systemd:
        name: firewalld
        enabled: yes
    -
      name: 'Show the status of firewallD service and save the output to resultF'
      command: service firewalld status
      register: resultF
    -
      name: 'Check if the service firewalld is not running and print the message to stdout'
      command: 'echo "Service is not active"'
      when: resultF.stdout.find('inactive') != -1
    -
      name: 'Install mariaDB'
      apt:
        name: mariadb-server
        state: present
    -
      name: 'Start the mariaDB service'
      service:
        name: mariadb
        state: started
    -
      name: 'Enable service mariadb'
      systemd:
        name: mariadb
        enabled: yes
    -
      name: 'Show the status of mariadb service and save the output to resultF'
      command: sudo service mariadb status
      register: resultM
    -
      name: 'Check if the service mariadb is running and print the message to stdout'
      command: 'echo "Mariadb serice is not running"'
      when: resultM.stdout.find('inactive') != -1
      command: 'echo "Mariadb serice is running"'
      when: resultM.stdout.find('active') != -1
    -
      name: 'Configure firewalld for database'
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp
    -
      name: 'Reload firewalld service'
      command: firewall-cmd --reload
    -
      name: 'Install python-mysql and python-pip'
      apt: name={{item}}
      with_items:
        - python3-pip
        - python3-mysqldb
    -
      name: 'Copy local sql script to target machine'
      copy:
        src: /home/entity/ansible-project/mariadb-script.sql
        dest: /home/mariadb-script.sql
    -
      name: 'Configure Database and Load Product Inventory Information to database'
      mysql_db:
        name: ecomdb
        state: import
        target: /home/mariadb-script.sql
    -
      name: 'Install php-mysql service'
      apt:
        name: php-mysql
        state: present
    -
      name: 'COnfigure firerwalld and reload'
      shell: firewall-cmd --permanent --zone=public --add-port=80/tcp && firewall-cmd --reload
