-
  name: 'Install and configure Kodecloud service'
  hosts: target1
  tasks:
    -
      name: 'Install FirewallD'
      apt:
        name: firewalld
        state: present
    -
      name: 'Start the firewallD service'
      service:
        name: firewalld
        state: started
    -
      name: 'Enable service firewalld'
      systemd:
        name: firewalld
        enabled: yes
    -
      name: 'Install mariaDB'
      apt:
        name: mariadb-server
        state: present
    -
      name: 'Start the mariaDB service'
      service:
        name: mariadb
        state: started
    -
      name: 'Enable service mariadb'
      systemd:
        name: mariadb
        enabled: yes
    -
      name: 'Configure firewalld for database'
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp
    -
      name: 'Reload firewalld service'
      command: firewall-cmd --reload
    -
      name: 'Install python-mysql and python-pip'
      apt: name={{item}}
      with_items:
        - python3-pip
        - python3-mysqldb
    -
      name: 'Copy local sql script to target machine'
      copy:
        src: /home/entity/ansible-project/mariadb-script.sql
        dest: /home/mariadb-script.sql
    -
      name: 'Configure Database and Load Product Inventory Information to database'
      mysql_db:
        name: ecomdb
        state: import
        target: /home/mariadb-script.sql
    -
      name: 'Install php-mysql, php and httpd service'
      apt:
        pkg:
          - apache2
          - php
          - php-mysql
        state: present
    -
      name: 'COnfigure firerwalld and reload'
      shell: firewall-cmd --permanent --zone=public --add-port=80/tcp && firewall-cmd --reload
    -
      name: 'Change DirectoryIndex index.html to DirectoryIndex index.php to make the php page the default page'
      lineinfile:
        path: /etc/apache2/apache2.conf
        line: "DirectoryIndex index.php"
        state: present
        insertafter: EOF
    -
      name: 'Start apache service'
      service:
        name: apache2
        state: started
    -
      name: 'Enable apache service'
      systemd:
        name: apache2
        enabled: yes
    -
      name: 'Install git'
      apt: 
        name: git
        state: present
    -
      name: 'Clear /var/www/html path, so that downloaded repository can be put in this directory'
      file:
        path: /var/www/html
        state: absent
    -
      name: 'Clone repository from github and put it into /var/www/html directory'
      shell: git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/
    -
      name: 'Update index.php file to connect to the right database server'
      lineinfile:
        path: /var/www/html/index.php
        regexp: '\$link = mysqli_connect'
        line: "\t\t\t$link = mysqli_connect('localhost', 'ecomuser', 'ecompassword', 'ecomdb');"
        state: present
    -  
      name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://localhost
